### ISSUE TITLE
any samples with PyTorch?

### ISSUE THREAD

**Issue by leaf918** [Mengman/TensorRT_Tutorial#1]
Thanks

**Comment by Mengman** [comment]
do you mean convert pytorch model into TensorRT?

**Comment by leaf918** [comment]
Yes,Pytorch 's RNN to tensorRT's rnn_v2

**Comment by Mengman** [comment]
sorry, I'm not very familiar with Pytorch's RNN,  you may try this repo https://github.com/NVIDIA-AI-IOT/torch2trt

**Comment by leaf918** [comment]
Thanks,but this repo does not contains any rnn op convertion.
